package org.cyy.fw.android.dborm;

import java.util.HashMap;
import java.util.Map;

/**
 * 
 * O-R map information<BR>
 * 
 * @author cyy
 * @version [V1.0, 2012-11-5]
 */
public class ORMapInfo {
	/**
	 * 
	 * relation info<BR>
	 * 
	 * @author cyy
	 * @version [V1.0, 2012-11-17]
	 */
	public static class AssociateInfo {
		private String field;
		private String sourceField;
		private Class<?> target;
		private String targetField;

		public String getField() {
			return field;
		}

		public String getSourceField() {
			return sourceField;
		}

		public Class<?> getTarget() {
			return target;
		}

		public String getTargetField() {
			return targetField;
		}

		public void setField(String field) {
			this.field = field;
		}

		public void setSourceField(String sourceField) {
			this.sourceField = sourceField;
		}

		public void setTarget(Class<?> target) {
			this.target = target;
		}

		public void setTargetField(String targetField) {
			this.targetField = targetField;
		}

	}

	/**
	 * relation info
	 */
	private Map<Class<?>, AssociateInfo> associateInfo = new HashMap<Class<?>, AssociateInfo>();
	/**
	 * Class
	 */
	private Class<?> clazz;
	/**
	 * 
	 * table column->class attribute mappings
	 */
	private Map<String, String> columnFieldMap = new HashMap<String, String>();
	/**
	 * class attribute->table column mappings
	 */
	private Map<String, String> fieldColumnMap = new HashMap<String, String>();
	/**
	 * Primary key generated by framework
	 */
	private boolean genUIDBySelf;
	/**
	 * auto-increment primary key
	 */
	private boolean pkSequence;

	private String primaryKeyColumn;

	private String primaryKeyField;

	private String tableName;

	public Map<Class<?>, AssociateInfo> getAssociateInfo() {
		return associateInfo;
	}

	public Class<?> getClazz() {
		return clazz;
	}

	public Map<String, String> getColumnFieldMap() {
		return columnFieldMap;
	}

	public Map<String, String> getFieldColumnMap() {
		return fieldColumnMap;
	}

	public String getPrimaryKeyColumn() {
		return primaryKeyColumn;
	}

	public String getPrimaryKeyField() {
		return primaryKeyField;
	}

	public String getTableName() {
		return tableName;
	}

	public boolean isGenUIDBySelf() {
		return genUIDBySelf;
	}

	public boolean isPkSequence() {
		return pkSequence;
	}

	public void setAssociateInfo(Map<Class<?>, AssociateInfo> associateInfo) {
		this.associateInfo = associateInfo;
	}

	public void setClazz(Class<?> clazz) {
		this.clazz = clazz;
	}

	public void setColumnFieldMap(Map<String, String> columnFieldMap) {
		this.columnFieldMap = columnFieldMap;
	}

	public void setFieldColumnMap(Map<String, String> columnMap) {
		this.fieldColumnMap = columnMap;
	}

	public void setGenUIDBySelf(boolean genUIDBySelf) {
		this.genUIDBySelf = genUIDBySelf;
	}

	public void setPkSequence(boolean pkSequence) {
		this.pkSequence = pkSequence;
	}

	public void setPrimaryKeyColumn(String primaryKeyColumn) {
		this.primaryKeyColumn = primaryKeyColumn;
	}

	public void setPrimaryKeyField(String primaryKeyField) {
		this.primaryKeyField = primaryKeyField;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

}
